# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Collection of thoughts and experiments.
email: agirorn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my site there are many like it but this one is mine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://agirorn.com" # the base hostname & protocol for your site
twitter_username: agirorn
github_username:  agirorn

# Build settings
markdown: kramdown
exclude: [
  '**/node_modules'
]
